# These are supported funding model platforms
ko_fi: cerebrux # Replace with a single Ko-fi username
liberapay: cerebrux # Replace with a single Liberapay username
custom: ["https://www.paypal.me/cerebrux"]
