language: bash
dist: dico

script:
  - mkdir -p Sysglance.AppDir/usr/bin ; cp sysglance.sh Sysglance.AppDir/usr/bin/
  - mkdir -p Sysglance.AppDir/usr/share/applications ; cp sysglance.desktop Sysglance.AppDir/usr/share/applications/
  - mkdir -p Sysglance.AppDir/usr/share/icons/hicolor/128x128/apps ; cp sysglance.png Sysglance.AppDir/usr/share/icons/hicolor/128x128/apps/
  - cp AppRun Sysglance.AppDir/
  - cp sysglance.desktop Sysglance.AppDir/
  - cp sysglance.png Sysglance.AppDir/
  - wget -c -nv "https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage"
  - chmod a+x appimagetool-x86_64.AppImage
  #- export VERSION=$(date +"%Y%m%d%k%M") # if I need a version I will use this for naming the file
  - ARCH=x86_64 ./appimagetool-x86_64.AppImage Sysglance.AppDir Sysglance-x86_64.AppImage
  #- chmod a+x Sysglance-x86_64.AppImage # needs investigation
after_success:
  - wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
  - bash upload.sh Sysglance-x86_64.AppImage

branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous.*)$/
